### PR TITLE
Fixed dependency problems

### PR DESCRIPTION
**Pull request by ajmeese7**
Same issue as with all the other PRs I'm about to make

### CODE REVIEW

**Comment by mayel** [comment]
Curious to know why you want to switch from using mess to deps in mix.ex?

**Comment by ajmeese7** [comment]
I didn't see any benefit to using an additional library when the dependencies are supported natively in `mix.ex`, but please correct me if I'm wrong. I'm looking to reduce software rot and minimize dependencies to mitigate bloat and to set the bar for entry lower for other developers that may be looking to contribute to the project

**Comment by jjl** [comment]
The purpose of mess is to take as much dependency resolution out of executable elixir code as possible and put it in convenient files which 'do the right thing' when you want to switch from a hex release to a git checkout or you want to overlay a local fork.

Aside from making some of this machine readable (deps.* files), it also gives us the ability to load different deps dependent on the flavour, something that would be significantly more fraught without it.

There is additionally the `messctl` utility you can use to edit them from the command line, if you like. Some of the makefile maintainer tasks use it.

**Comment by jjl** [comment]
There is I think a more general problem which mess is a symptom of, that we are quite unlike any other elixir application i've seen in some of the things we try to enable and it confuses the tools built for the 99% case where the app developer is the person who is going to deploy it.

At the moment, what we have for this is a pile of hacks that were "just enough". A lot of them will be replaced by the custom scriptable build tool i've been designing to do a better job of all of this.

**Comment by ajmeese7** [comment]
Thanks for explaining! I'll close out this PR now, I anxiously look forwards to the upcoming changes and I'm more than happy to help with anything I can do to make the process easier on you all.

Feel free to hit me up if needed!

**Comment by jjl** [comment]
at the moment, i think docs are probably the easiest thing to help out with - it's hard for a newbie to get a general feel for how the project is structured.

by the end of this week i hope to have dealt with replacing some of our crufty queries and generally making some of the code a bit less confusing in the contexts.

**Pull request closed without merging**
